"""Update review: make rating_id nullable

Revision ID: 03d0e41678a7
Revises: 9b1784e4db9b
Create Date: 2025-03-22 13:31:13.615272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d0e41678a7'
down_revision: Union[str, None] = '9b1784e4db9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'rating_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
