"""Update User table: make name and surname nullable

Revision ID: c4f7686c33f6
Revises: aab09a941d34
Create Date: 2025-03-16 15:41:31.304813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f7686c33f6'
down_revision: Union[str, None] = 'aab09a941d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
